version: “3.7”
services:
  projeto-bar:
    build: .
    ports:
      - "8080:8080"
    environment:
      IP: mysql
      USERNAME_DB: root
      DATABASE: projetoBar
      PASSWORD_DB: teste
    depends_on:
      - mysql
    networks:
      - projetobar
    volumes:
      - ./app:/usr/src/app
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: projetoBar
    ports:
      - "3306:3306"
    restart: always
    networks:
      - projetobar
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  projetobar:
    driver: bridge



